/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mertFrenSol from "./MertFren.sol";
export type { mertFrenSol };
import type * as mertSpeicalNftSol from "./MertSpeicalNFT.sol";
export type { mertSpeicalNftSol };
