/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMonadOneMillion,
  IMonadOneMillionInterface,
} from "../../../contracts/MertFren.sol/IMonadOneMillion";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMonadOneMillion__factory {
  static readonly abi = _abi;
  static createInterface(): IMonadOneMillionInterface {
    return new Interface(_abi) as IMonadOneMillionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMonadOneMillion {
    return new Contract(address, _abi, runner) as unknown as IMonadOneMillion;
  }
}
