/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMonadOneMillion__factory } from "./IMonadOneMillion__factory";
export { MertFren__factory } from "./MertFren__factory";
